name: getx_news_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5 # GetX
  http: ^0.13.5 # API通信用
  flutter_config: ^2.0.0 # APIKey読み込み用
  url_launcher: ^6.1.10 # リンク表示用

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  mockito: ^5.4.0 # テスト用

flutter:
  uses-material-design: true
